import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/src/lib/shared/auth';
import { getAllCertificates, type CertRow } from '@/src/lib/training/sheets';
import { getServerClient } from '@/src/lib/shared/supabase';

export const revalidate = 0;

// POST - sync issued certificates from Apps Script → Supabase (status + basic metadata)
export async function POST() {
  const session = await getServerSession(authOptions);
  if (!session?.user || (session.user as { role?: string }).role !== 'admin') {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  const certsRes = await getAllCertificates();
  if (!certsRes.success) {
    return NextResponse.json({ error: 'Failed to fetch certificates from Apps Script' }, { status: 500 });
  }

  const rows = certsRes.data ?? [];
  const sb   = getServerClient();

  let synced  = 0;
  let skipped = 0;

  for (const row of rows) {
    // Skip non-issued rows
    if (row.certStatus !== 'Issued') { skipped++; continue; }
    if (!row.registrationId)         { skipped++; continue; }

    // Only sync metadata - don't overwrite cert_pdf_url / badge_url generated by engine
    const { error } = await sb
      .from('student_certificates')
      .upsert(
        {
          registration_id:   row.registrationId,
          full_name:         row.fullName,
          email:             row.email,
          course:            row.course,
          completion_date:   row.completionDate || null,
          final_exam_score:  row.finalExamScore || null,
          avg_session_score: row.avgSessionScore || null,
          cert_status:       'Issued',
          issued_date:       row.issuedDate || null,
          synced_at:         new Date().toISOString(),
        },
        { onConflict: 'registration_id' },
      );

    if (error) { console.error('[cert-sync]', error); skipped++; }
    else         synced++;
  }

  // Update last-synced timestamp
  await sb
    .from('training_settings')
    .upsert({ key: 'cert_last_synced', value: new Date().toISOString() }, { onConflict: 'key' });

  return NextResponse.json({ ok: true, synced, skipped });
}

// GET - return list of certificates from Supabase
export async function GET() {
  const session = await getServerSession(authOptions);
  if (!session?.user || (session.user as { role?: string }).role !== 'admin') {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  const sb = getServerClient();

  const [certsRes, settingRes] = await Promise.all([
    sb.from('student_certificates').select('*').order('issued_date', { ascending: false }),
    sb.from('training_settings').select('value').eq('key', 'cert_last_synced').single(),
  ]);

  return NextResponse.json({
    certs:      certsRes.data ?? [],
    lastSynced: settingRes.data?.value ?? null,
  });
}
