/**
 * periodAxis.ts
 *
 * Universal results-table period axis builder. Every results table that
 * has a period axis (Tab 3 Results Tables 1-4, Tab 4 Inputs Summary
 * Funding / Debt / Equity, Tab 4 Schedules) routes through
 * `buildResultsPeriodAxis()` so the layout is consistent: one prior
 * column at index 0 (calendar period immediately before the first
 * active period) followed by the active labels generated by the
 * existing `generatePeriodLabels` core helper.
 *
 * Examples (matches the universal-formatting brief):
 *   - Annual,  project starts Dec 26 -> [Dec 25, Dec 26, Dec 27, ...]
 *   - Quarterly, starts Q1 26       -> [Q4 25, Q1 26, Q2 26, ...]
 *   - Monthly, starts Jan 26        -> [Dec 25, Jan 26, Feb 26, ...]
 *
 * The prior column is always rendered (blank / zero values, no math
 * change). The brief: pure formatting / layout, no engine change.
 */

import { generatePeriodLabels } from '@/src/core/calculations';
import type { OutputGranularity } from '../../../lib/state/module1-types';

export interface ResultsPeriodAxis {
  /** Calendar period immediately before activeLabels[0]. */
  priorLabel: string;
  /** Active period labels (project axis, post any caller-side crop). */
  activeLabels: string[];
  /** [priorLabel, ...activeLabels]. The full axis a table renders. */
  labels: string[];
  /** Total column count: 1 prior + activeLabels.length. */
  count: number;
}

/**
 * Build the period axis for a results table.
 *
 * `numAnnualPeriods` is the count of project years rendered at the
 * caller's granularity (the caller already applied its own 60-year cap
 * + any data-driven crop). The helper expands to the requested
 * granularity by calling `generatePeriodLabels(startIso, numAnnualPeriods, granularity)`.
 *
 * `cropAnnualOffset` shifts the active range by N years forward (Tab 3
 * Results uses this to crop leading zero years). The prior label is
 * one sub-period BEFORE activeLabels[0], not before project start, so
 * it always sits flush against the rendered range.
 */
export function buildResultsPeriodAxis(opts: {
  startIso: string;
  granularity: OutputGranularity;
  numAnnualPeriods: number;
  cropAnnualOffset?: number;
}): ResultsPeriodAxis {
  const cropOffset = Math.max(0, opts.cropAnnualOffset ?? 0);
  const subPerYear =
    opts.granularity === 'annual' ? 1 : opts.granularity === 'quarterly' ? 4 : 12;
  const allLabels = generatePeriodLabels(
    opts.startIso,
    cropOffset + Math.max(0, opts.numAnnualPeriods),
    opts.granularity,
  );
  const activeLabels = allLabels.slice(cropOffset * subPerYear);
  // Prior calendar period: one annual year before activeLabels[0].
  // Annual / quarterly / monthly each have a fixed convention so the
  // result reads naturally regardless of granularity.
  const start = new Date(opts.startIso);
  const startYear = Number.isNaN(start.getTime())
    ? new Date().getUTCFullYear()
    : start.getUTCFullYear();
  const priorYear = startYear + cropOffset - 1;
  const yy = String(priorYear).slice(-2).padStart(2, '0');
  let priorLabel: string;
  if (opts.granularity === 'annual') {
    priorLabel = `Dec ${yy}`;
  } else if (opts.granularity === 'quarterly') {
    priorLabel = `Q4 ${yy}`;
  } else {
    priorLabel = `Dec ${yy}`;
  }
  const labels = [priorLabel, ...activeLabels];
  return { priorLabel, activeLabels, labels, count: labels.length };
}
