-- ============================================================
-- 059: Seed home page Founder section into page_sections
-- Editable via Admin CMS; layout stays in custom JSX
-- ============================================================

DELETE FROM page_sections WHERE page_slug = 'home' AND section_type = 'team';

INSERT INTO page_sections (page_slug, section_type, display_order, visible, content, styles) VALUES
('home', 'team', 7, true,
 '{"badge":"The Founder","name":"Ahmad Din","title":"Corporate Finance & Transaction Advisory Specialist | Financial Modeling Expert","bio":"Corporate Finance and Transaction Advisory specialist with deep expertise in financial modeling across real estate, business valuation, and corporate finance.","credentials":["12+ years in Corporate Finance & Advisory","Experience across KSA & Pakistan","Lender-grade models: IRR, DSCR, Feasibility","Real estate, energy, infrastructure & industrial sectors","Transaction advisory & investment support"],"photo_url":"","photo_alt":"Ahmad Din","photo_height":"320px","photo_fit":"cover","photo_radius":"16px","linkedin_url":"","cta_primary_text":"Read Full Profile →","cta_primary_url":"/about/ahmad-din","cta_secondary_text":"Connect on LinkedIn →","cta_secondary_url":"","booking_text":"Book a Meeting","booking_url":"","show_read_more":true,"read_more_label":"Read Full Profile →","long_bio":"Ahmad Din has spent over 15 years at the intersection of real estate development and structured finance. His career spans deal origination, feasibility analysis, development financing, and investor relations across the GCC, Southeast Asia, and international markets.\n\nBefore founding Financial Modeler Pro, Ahmad worked with major real estate developers and advisory firms, building financial models for projects ranging from luxury residential towers to large-scale mixed-use developments. He noticed that the same spreadsheet problems — inconsistent assumptions, untraceable errors, and hours spent reformatting for investor presentations — kept appearing on every engagement.\n\nFinancial Modeler Pro was built to solve that problem once and for all: a structured, professional-grade platform that produces audit-ready models and investor-ready outputs without the spreadsheet overhead.","philosophy":"A good financial model is not just a calculation — it''s a communication tool. Every assumption should be visible, every output should be traceable, and the final product should be something you''d be proud to present to a board or an investor committee without reformatting.","experience":["15+ years in real estate finance and development advisory","Structured financing for projects across GCC, SEA, and international markets","Built financial models for residential, hospitality, and mixed-use developments","Worked with developers, sovereign funds, and institutional investors","Founded Financial Modeler Pro to democratize professional-grade modeling"]}',
 '{"bgColor":"#1B3A6B","textColor":"#ffffff","paddingY":"64px 40px 80px"}');
